/*
 * This Java source file was generated by the Gradle 'init' task.
 * Find four elements that sum to a given value.
 */
package elem;

// A hashing based Java program to find 
// if there are four elements with given sum. 
import java.util.HashMap; 
import java.util.ArrayList;

public class App { 
	static class pair { 
		int first, second; 
		public pair(int first, int second) 
		{ 
			this.first = first; 
			this.second = second; 
		} 
	} 

	// The function finds four elements 
	// with given sum X 
	static void findFourElements( 
        int arr[],
		int n, int X) 
	{ 
		// Store sums of all pairs in a hash table 
		HashMap<Integer, pair> mp = new HashMap<Integer, pair>(); 
        ArrayList<Integer> visited = new ArrayList<Integer>(); 
		for (int i = 0; i < n - 1; i++) 
			for (int j = i + 1; j < n; j++) 
				mp.put(arr[i] + arr[j], 
					new pair(i, j)); 

		// Traverse through all pairs and search 
		// for X - (current pair sum). 
		for (int i = 0; i < n - 1; i++) { 
			for (int j = i + 1; j < n; j++) { 
				int sum = arr[i] + arr[j]; 

				// If X - sum is present in hash table, 
				if (mp.containsKey(X - sum)) { 

					// Making sure that all elements are 
					// distinct array elements and an element 
					// is not considered more than once. 
					pair p = mp.get(X - sum);
                    if (!visited.contains(arr[i]) || 
                    !visited.contains(arr[j]) ||
                    !visited.contains(arr[p.first]) ||
                    !visited.contains(arr[p.second])) {
                        visited.add(arr[i]);
                        visited.add(arr[j]);
                        visited.add(arr[p.first]);
                        visited.add(arr[p.second]);

                        System.out.println( 
							arr[i] + ", " + arr[j] 
							+ ", " + arr[p.first] 
							+ ", " + arr[p.second]); 
                    }
                    
				} 
			} 
		} 
	} 

	// Driver Code 
	public static void main(String[] args) 
	{ 
		int arr[] = {1, 3, 2, 4, 8, 9, 5}; 
		int n = arr.length; 
		int X = 14; 
		findFourElements(arr, n, X); 
	} 
} 

// This code is contributed by Princi Singh 
